### ISSUE TITLE
[feature] allow prisma client to be imported from non-default location

### ISSUE THREAD

**Issue by thyming** [Quramy/jest-prisma#29]
Hi, I'm wondering what you think about supporting a non-default prisma import location. I think it may end up complicating things quite a bit but perhaps it's possible to do with dynamic import. Wish I could use this out of the box!

**Comment by pranas** [comment]
We also use custom `output` for our Prisma clients (needed when you have multiple projects in monorepo using their own Prisma schemas). For now, the simplest solution was to copy over `environment.ts` to our project and set `testEnvironment: './src/jest-prisma-environment.ts'`. Looking forward to a solution for this issue so we can go back to importing this package instead.

**Comment by arthurfiorette** [comment]
For those wondenring a solution. `moduleNameMapper` jest option can work for this.

```js
// jest.config.js
module.exports = {
  moduleNameMapper: {
    '^\\@prisma/client$': '<rootDir>/my-prisma-folder'
  },
};


```

**Comment by arthurfiorette** [comment]
Hey guys, I've published [`@arthurfiorette/jest-prisma`](https://github.com/arthurfiorette/jest-prisma) in the meanwhile, if anyone is interested.

**Comment by TakuroSugahara** [comment]
Hi @arthurfiorette 
Thank you for great job.

I tried it and confirmed that it works but I encountered a type error.
I worked around it by doing the following. Is there any other way to avoid this?

```ts
import { PrismaClient } from './generated/my-prisma'

const testPrisma = jestPrisma.client as unknown as PrismaClient
```
