### ISSUE TITLE
Publication and development of libraries for vitest.

### ISSUE THREAD

**Issue by aiji42** [Quramy/jest-prisma#44]
This library has greatly improved our testing experience, thank you.

I am currently working personally on a library that optimizes @quramy/jest-prisma for vitest, would you please allow me to publish it in a new npm under my name?
- It will be a library that includes `jest-prisma-core` as a dependency
- I will include a reference link to this repository, acknowledgements, etc. in the README.

In the meantime, I considered including the vitest version of the library in this repository, but
- Since this repository is **jest**-prisma, including the vitest context would be confusing
- The library name must be `virest-environment-${name}` and cannot contain the `@quramy/*` namespace.
    - https://vitest.dev/guide/environment.html#test-environment

For these reasons, we think it is better to separate repositories.

**Comment by Quramy** [comment]
Thanks.

> we think it is better to separate repositories.

I agree your consideration absolutely 😄

**Comment by aiji42** [comment]
Thank you for your agreement😊
Now I would like to proceed with the release of the package.

**Comment by aiji42** [comment]
I was able to release it successfully.
Once again, thank you for developing the very useful library jest-prisma👍
