### ISSUE TITLE
⚠️  Client extension does not work ⚠️ 

### ISSUE THREAD

**Issue by Quramy** [Quramy/jest-prisma#47]
About https://www.prisma.io/docs/concepts/components/prisma-client/client-extensions

jest-prisma must not disturb usage of this features.

**Comment by Quramy** [comment]
I investigated client extension with #50 .

I found critical problem: **transactional client and model in tx client are not extended**. 

And I reported this problem: https://github.com/prisma/prisma/issues/16582

**Comment by arthurfiorette** [comment]
Hey @Quramy, https://github.com/prisma/prisma/issues/16582 was fixed, any news?

**Comment by Quramy** [comment]
Yep, I'll restart to work #50 .

**Comment by arthurfiorette** [comment]
Could you release #75?

**Comment by Uki884** [comment]
When do you expect this problem to be fixed?

**Comment by arthurfiorette** [comment]
I'm fixing some problems at `@arthurfiorette/jest-prisma`, in case you wanna check it out.
